# Generated by Django 5.2.12 on 2026-03-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('fill_level', models.IntegerField()),
                ('capacity', models.IntegerField(default=100)),
            ],
        ),
    ]
