# Generated by Django 5.2.12 on 2026-03-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bin',
            name='y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
